dna = 'ATTGGAGGCCGACTCCTAGCATTTGTTAGTTTTCTGCGAAACCAGACTAGTGGCCGTGCCGGAAGAAATGTAGTCTTTTCCCATAACGTTTTTCACAAACCAGGTACGGTCCTTGTACTGATATATTTATTCCTCTCGGCCAACTACTGAAGGGATTACTTACAGTCGCACTATGAGAGTGTTCTCGAGCATCTGCTCAGGTAGAATGCATTGATCACACCCTATCAGTTTTTTCGTGGCTCTTATCCACGGAAGTTGTTAGAGGGGGGTACGGTGTTAAATCCCTTTCGAATAGCTCTAGTCGTCCGGCGTAGCGGTATGTGGCCGTCTGGTCTTGAATAGTGGTCGTTAGATGCGGGCCATGGAGATTCCGTAGATCTCGGGGTTCTGAGATTGCACGTGCGGTTCAACATCAGAAGGACCGCCCTGATGGGCTGTTGCTGATAACATTCGTCATCATTATGAGCTGTTCTGCTACCTTAGCTGCAAGGATGTTATTTGGACTCGGTTCATCTGTACATGGTCTACTTGGCACCCCGAACACTTTCCTAAACCATATCGCCCCAAATTTTTTCTTTTCTTGCGGTTGTGTTAGTCTTATCTGACCGACCCATTCAAAGGACCGTACCGCATGGGTCCTAGCATTAAACTGTATAATTTCAGATCAACGGTCTCCGCTGCCATATTCGCCGATGTACTAGCTTACTTCTATTGGTTGGAAAGATGGCACCCCATTCGTTCGGGGACAACCTCCTGGCCATCCGCAAAGGGCCGGGTGAGTGTGCGTAACACTATCAACCTGCTCGTAAGTTTTATTTTAACTCCGACCATCCGTTGCATCCGACCTCCCTGATATACCATATCTTATAGATCTGAGGTAGTTCACC'
comp_dna = ''
for c in dna:
    if c == 'A':
        comp_dna = 'T' + comp_dna
    elif c == 'C':
        comp_dna = 'G' + comp_dna
    elif c == 'G':
        comp_dna = 'C' + comp_dna
    elif c == 'T':
        comp_dna = 'A' + comp_dna

print(comp_dna)
